const { fontFamily } = require('tailwindcss/defaultTheme');

module.exports = {
  errorOnInvalidVariant: false,
  content: [
    './layouts/**/*.html',
    './content/**/*.{html,md}',
    './assets/**/*.js',
    './themes/blowfish/layouts/**/*.html',
    './themes/blowfish/content/**/*.{html,md}',
    './node_modules/tw-elements/js/**/*.js',
    './themes/**/layouts/**/*.html',
  ],
  safelist: [
    'w-48',
    'w-[12rem]',
    'max-w-[12rem]',
    'lg:grid-cols-3',
    'xl:grid-cols-3',
    '2xl:grid-cols-4',
    { pattern: /^rtl:/ },
  ],
  darkMode: 'class',
  theme: {
    extend: {
      height: {
        '20': '4rem',
        '22': '5rem',
      },
      fontFamily: {
        sans: ['Urbanist', ...fontFamily.sans],
        mono: ['JetBrains Mono', ...fontFamily.mono],
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.neutral.700 / 1'),
            '--tw-prose-headings': theme('colors.neutral.800 / 1'),
            '--tw-prose-lead': theme('colors.neutral.500 / 1'),
            '--tw-prose-links': theme('colors.primary.600 / 1'),
            '--tw-prose-bold': theme('colors.neutral.900 / 1'),
            '--tw-prose-counters': theme('colors.neutral.800 / 1'),
            '--tw-prose-bullets': theme('colors.neutral.500 / 1'),
            '--tw-prose-hr': theme('colors.neutral.200 / 1'),
            '--tw-prose-quotes': theme('colors.neutral.700 / 1'),
            '--tw-prose-quote-borders': theme('colors.primary.200 / 1'),
            '--tw-prose-captions': theme('colors.neutral.500 / 1'),
            '--tw-prose-code': theme('colors.secondary.700 / 1'),
            '--tw-prose-pre-code': theme('colors.neutral.700 / 1'),
            '--tw-prose-pre-bg': theme('colors.neutral.50 / 1'),
            '--tw-prose-th-borders': theme('colors.neutral.500 / 1'),
            '--tw-prose-td-borders': theme('colors.neutral.300 / 1'),
            '--tw-prose-invert-body': theme('colors.neutral.300 / 1'),
            '--tw-prose-invert-headings': theme('colors.neutral.50 / 1'),
            '--tw-prose-invert-lead': theme('colors.neutral.500 / 1'),
            '--tw-prose-invert-links': theme('colors.primary.400 / 1'),
            '--tw-prose-invert-bold': theme('colors.neutral.DEFAULT / 1'),
            '--tw-prose-invert-counters': theme('colors.neutral.400 / 1'),
            '--tw-prose-invert-bullets': theme('colors.neutral.600 / 1'),
            '--tw-prose-invert-hr': theme('colors.neutral.500 / 1'),
            '--tw-prose-invert-quotes': theme('colors.neutral.200 / 1'),
            '--tw-prose-invert-quote-borders': theme('colors.primary.900 / 1'),
            '--tw-prose-invert-captions': theme('colors.neutral.400 / 1'),
            '--tw-prose-invert-code': theme('colors.secondary.400 / 1'),
            '--tw-prose-invert-pre-code': theme('colors.neutral.200 / 1'),
            '--tw-prose-invert-pre-bg': theme('colors.neutral.700 / 1'),
            '--tw-prose-invert-th-borders': theme('colors.neutral.500 / 1'),
            '--tw-prose-invert-td-borders': theme('colors.neutral.700 / 1'),
            a: {
              textDecoration: 'none',
              textDecorationColor: theme('colors.primary.300 / 1'),
              fontWeight: '500',
              '&:hover': {
                color: theme('colors.primary.600 / 1'),
                textDecoration: 'none',
                borderRadius: '0.09rem',
              },
            },
            'a code': {
              color: 'var(--tw-prose-code)',
            },
            kbd: {
              backgroundColor: theme('colors.neutral.200 / 1'),
              padding: '0.1rem 0.4rem',
              borderRadius: '0.25rem',
              fontSize: '0.9rem',
              fontWeight: '600',
            },
            mark: {
              color: theme('colors.neutral.800 / 1'),
              backgroundColor: theme('colors.primary.600 / 1'),
              padding: '0.1rem 0.2rem',
              borderRadius: '0.25rem',
            },
            code: {
              backgroundColor: theme('colors.neutral.50 / 1'),
              paddingTop: '3px',
              paddingBottom: '3px',
              paddingLeft: '5px',
              paddingRight: '5px',
              borderRadius: '0.25rem',
            },
            'code::before': { display: 'none' },
            'code::after': { display: 'none' },
            'p::before': { display: 'none' },
            'p::after': { display: 'none' },
            'a.active': {
              'text-decoration-color': theme('colors.primary.600 / 1'),
            },
            'p.active': {
              'text-decoration-color': theme('colors.primary.600 / 1'),
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('tailwind-scrollbar')({ preferredStrategy: 'pseudoelements' }),
  ],
};
